### ISSUE TITLE
Relation one2one in the data

### ISSUE THREAD

**Issue by hoanglam-novobi** [Featuretools/featuretools#307] opened 2018-11-02 03:58 UTC
### Bug/Feature Request Description

I have some problem when I try to use the featuretools to create new features with my data.
The structure of the data is:
- Input table: the index is the timestamp (the format is %m-%d-%Y %H:%M:%S)
- Target table: a column with the class label (1 or 0) and one is the timestamp.
The relation between two table is one2one (input_table.timestamp -> target_table.timestamp).

When I ran DFS with this entity set. I got an error with the message "TypeError: group() got an unexpected keyword argument 'observed'".

Does anybody have the solution for this situation or any suggestion?

Many thanks.

**Comment by kmax12** [comment] 2018-11-02 15:49
@hoanglam-novobi This error is related to changes to Pandas API. Can you make sure you're on the latest version -- pandas 0.23.4?

**Comment by hoanglam-novobi** [comment] 2018-11-02 16:33
Thanks or reply.
I have checked the version of pandas. My version of pandas is 0.23.4.

**Comment by hoanglam-novobi** [comment] 2018-11-02 16:35
Thanks or reply.
I have checked the version of pandas. My version of pandas is 0.23.4.

**Comment by kmax12** [comment] 2018-11-02 18:19
to better help, can you share a reproducible code example, as well as the full stack trace?

**Comment by jbdatascience** [comment] 2018-11-19 13:10
I experience the same problem:

I am trying out Automated Feature Engineering with Featuretools version 0.4.0 on Google Colab.

Although I do NOT encounter problems when I run this on my local computer on Anaconda Jupyter Notebook, but when I run the exact same Notebook on Google Colab, I always get the same error !

I use the Notebook Automated_Feature_Engineering.ipynb, which is mentioned in the article "Automated Feature Engineering in Python. How to automatically create machine learning features". (https://towardsdatascience.com/automated-feature-engineering-in-python-99baf11cc219).

The link to that Notebook is:
https://github.com/WillKoehrsen/automated-feature-engineering/blob/master/walk_through/Automated_Feature_Engineering.ipynb


The error I get arises in this part of the Python code in that Notebook:

# Create new features using specified primitives
features, feature_names = ft.dfs(entityset = es, target_entity = 'clients', 
                                 agg_primitives = ['mean', 'max', 'percent_true', 'last'],
                                 trans_primitives = ['years', 'month', 'subtract', 'divide'])


The complete error message:

TypeError Traceback (most recent call last) <ipython-input-25-a57ec028599a> in <module>() 1 features, feature_names = ft.dfs(entityset = es, target_entity = 'clients', 2 agg_primitives = ['mean', 'max', 'percent_true', 'last'], ----> 3 trans_primitives = ['years', 'month', 'subtract', 'divide']) /usr/local/lib/python3.6/dist-packages/featuretools/synthesis/dfs.py in dfs(entities, relationships, entityset, target_entity, cutoff_time, instance_ids, agg_primitives, trans_primitives, allowed_paths, max_depth, ignore_entities, ignore_variables, seed_features, drop_contains, drop_exact, where_primitives, max_features, cutoff_time_in_index, save_progress, features_only, training_window, approximate, chunk_size, n_jobs, dask_kwargs, verbose) 211 n_jobs=n_jobs, 212 dask_kwargs=dask_kwargs, --> 213 verbose=verbose) 214 return feature_matrix, features /usr/local/lib/python3.6/dist-packages/featuretools/computational_backends/calculate_feature_matrix.py in calculate_feature_matrix(features, entityset, cutoff_time, instance_ids, entities, relationships, cutoff_time_in_index, training_window, approximate, save_progress, verbose, chunk_size, n_jobs, dask_kwargs, profile) 260 cutoff_df_time_var=cutoff_df_time_var, 261 target_time=target_time, --> 262 pass_columns=pass_columns) 263 264 feature_matrix = pd.concat(feature_matrix) /usr/local/lib/python3.6/dist-packages/featuretools/computational_backends/calculate_feature_matrix.py in linear_calculate_chunks(chunks, features, approximate, training_window, profile, verbose, save_progress, entityset, no_unapproximated_aggs, cutoff_df_time_var, target_time, pass_columns) 523 cutoff_df_time_var, 524 target_time, pass_columns, --> 525 backend=backend) 526 feature_matrix.append(_feature_matrix) 527 # Do a manual garbage collection in case objects from calculate_chunk /usr/local/lib/python3.6/dist-packages/featuretools/computational_backends/calculate_feature_matrix.py in calculate_chunk(chunk, features, approximate, training_window, profile, verbose, save_progress, no_unapproximated_aggs, cutoff_df_time_var, target_time, pass_columns, backend, entityset) 344 ids, 345 precalculated_features=precalculated_features, --> 346 training_window=window) 347 348 id_name = _feature_matrix.index.name /usr/local/lib/python3.6/dist-packages/featuretools/computational_backends/utils.py in wrapped(*args, **kwargs) 32 def wrapped(*args, **kwargs): 33 if save_progress is None: ---> 34 r = method(*args, **kwargs) 35 else: 36 time = args[0].to_pydatetime() /usr/local/lib/python3.6/dist-packages/featuretools/computational_backends/calculate_feature_matrix.py in calc_results(time_last, ids, precalculated_features, training_window) 318 precalculated_features=precalculated_features, 319 ignored=all_approx_feature_set, --> 320 profile=profile) 321 return matrix 322 /usr/local/lib/python3.6/dist-packages/featuretools/computational_backends/pandas_backend.py in calculate_all_features(self, instance_ids, time_last, training_window, profile, precalculated_features, ignored, verbose) 196 197 handler = self._feature_type_handler(test_feature) --> 198 result_frame = handler(group, input_frames) 199 200 output_frames_type = self.feature_tree.output_frames_type(test_feature) /usr/local/lib/python3.6/dist-packages/featuretools/computational_backends/pandas_backend.py in _calculate_agg_features(self, features, entity_frames) 458 # work) 459 to_merge = base_frame.groupby(base_frame[groupby_var], --> 460 observed=True, sort=False).agg(to_agg) 461 # rename columns to the correct feature names 462 to_merge.columns = [agg_rename["-".join(x)] for x in to_merge.columns.ravel()] /usr/local/lib/python3.6/dist-packages/pandas/core/generic.py in groupby(self, by, axis, level, as_index, sort, group_keys, squeeze, **kwargs) 5160 .. deprecated:: 0.21.0 5161 -> 5162 Parameters 5163 ---------- 5164 convert_dates : boolean, default True /usr/local/lib/python3.6/dist-packages/pandas/core/groupby.py in groupby(obj, by, **kwds) /usr/local/lib/python3.6/dist-packages/pandas/core/groupby.py in __init__(self, obj, keys, axis, level, grouper, exclusions, selection, as_index, sort, group_keys, squeeze, **kwargs) /usr/local/lib/python3.6/dist-packages/pandas/util/_validators.py in validate_kwargs(fname, kwargs, compat_args) 154 """ 155 kwds = kwargs.copy() --> 156 _check_for_invalid_keys(fname, kwargs, compat_args) 157 _check_for_default_values(fname, kwds, compat_args) 158 /usr/local/lib/python3.6/dist-packages/pandas/util/_validators.py in _check_for_invalid_keys(fname, kwargs, compat_args) 125 raise TypeError(("{fname}() got an unexpected " 126 "keyword argument '{arg}'". --> 127 format(fname=fname, arg=bad_arg))) 128 129 

TypeError: group() got an unexpected keyword argument 'observed'

**Comment by hoanglam-novobi** [comment] 2018-11-20 06:55
@jbdatascience Thanks for sharing.
I looked at your notebook. But it seems like the relationship in your data is still one2many. For example,
a client_id has many loan_id...
I also have this error when I try to run dfs in featuretools in Google Colab. 
Have you ever try to run dfs with the relation one2one in your data?

**Comment by hoanglam-novobi** [comment] 2018-11-20 07:13
@kmax12 
Sorry for late reply. I don't have time to look again at this problem until now.
With the lastest run, I run dfs in my computer and it's successful.
I'm try to predict stock price based on historical data.
More detail about the code I ran:
The input table: the index column is the timestamp and some potential variable (continuous value)
The target table: the index column is also the timestamp and column ``price` (continuous value) is target column I want to predict.
The relationship is one2one: input_table.timestamp -> target_table.timestamp
I want to use DFS in featuretools to create more features that may help me to increase the accuracy of the model.

Here is some code I run:
# create EntitySet
es = ft.EntitySet(id="stock")
es = es.entity_from_dataframe(entity_id = 'input', dataframe = input_df, index='timestamp')
es = es.entity_from_dataframe(entity_id = 'target', dataframe = target_df, index='timestamp')

# create relation
r_real_time_target = ft.Relationship(es['target']['timestamp'],
                                                         es['input']['timestamp'])

# add the relationship to the entity set
es = es.add_relationship(r_real_time_target)

feature_matrix, feature_defs = ft.dfs(entityset=es, 
                                    target_entity="input", 
                                    agg_primitives=['count', 'mean', 'sum', 'skew', 'mode', 'avg_time_between'],
                                    trans_primitives=['divide'],
                                    verbose=True,
                                    max_depth=1)

With the previous definition about entity set and relationship, do featuretools create new features to predict target value?

**Comment by jbdatascience** [comment] 2018-11-20 16:20
> @jbdatascience Thanks for sharing.
> I looked at your notebook. But it seems like the relationship in your data is still one2many. For example,
> a client_id has many loan_id...
> I also have this error when I try to run dfs in featuretools in Google Colab.
> Have you ever try to run dfs with the relation one2one in your data?

I think the relationship in my data has to be one2many in the case of a client that can have more than one loan ! So a one2one relation would not be appropriate for this case.
But perhaps you mean one2one realtion as a technical work-around for the problem at hand ("TypeError: group() got an unexpected keyword argument 'observed'", which seems to be a Pandas related error ...) ?

**Comment by kmax12** [comment] 2018-11-26 17:12
If your data does in fact have a 1 to 1 relationship, you should just combine the entities into one entity!

Closing this issue for now.

**Closed by kmax12** 2018-11-26 17:12 UTC
