### ISSUE TITLE
Setting cutoff_time to values lower than the row's current time_index fails aggregation

### ISSUE THREAD

**Issue by antontarasenko** [Featuretools/featuretools#184] opened 2018-07-05 15:27 UTC
### Bug Description

I'm generating historical features for the current row. For example, the number of transactions made in the last hour during a session.

I set `cutoff_time` as `time_index value - 1 second`, so I expect the features to be based on historical data minus the current row. This allows including the response variable from historical rows.

The problem is, when this parameter does not equal the `time_index` variable, I get a bunch of `NaN`s in the original *and* generated features.

The code:

```py
#!/usr/bin/env python3

import featuretools as ft
import pandas as pd
from featuretools import primitives, variable_types

data = ft.demo.load_mock_customer()

transactions_df = data['transactions']
# ISSUE: 
transactions_df['cutoff_time'] = transactions_df['transaction_time'] - pd.Timedelta(seconds=1)

es = ft.EntitySet('transactions_set')
es.entity_from_dataframe(
    entity_id='transactions',
    dataframe=transactions_df,
    variable_types={
        'transaction_id': variable_types.Index,
        'session_id': variable_types.Id,
        'transaction_time': variable_types.DatetimeTimeIndex,
        'product_id': variable_types.Id,
        'amount': variable_types.Numeric,
        'cutoff_time': variable_types.Datetime
    },
    index='transaction_id',
    time_index='transaction_time'
)
es.normalize_entity(
    base_entity_id='transactions',
    new_entity_id='sessions',
    index='session_id'
)
es.add_last_time_indexes()

fm, features = ft.dfs(
    entityset=es,
    target_entity='transactions',
    agg_primitives=[primitives.Sum, primitives.Count],
    trans_primitives=[primitives.Day],
    cutoff_time=transactions_df[['transaction_id', 'cutoff_time']].
        rename(index=str, columns={'transaction_id': 'transaction_id', 'cutoff_time': 'time'}),
    training_window='1 hours',
    verbose=True
)

print(fm)
```

Output (excerpt):

```
                DAY(cutoff_time)  sessions.SUM(transactions.amount)  \
transaction_id                                                        
352                          NaN                                NaN   
186                          NaN                                NaN   
319                          NaN                                NaN   
256                          NaN                                NaN   
449                          NaN                                NaN   
40                           NaN                                NaN   
13                           NaN                                NaN   
127                          NaN                                NaN   
21                           NaN                                NaN   
309                          NaN                                NaN   
```

Column `sessions.SUM(transactions.amount)` is supposed to be >= 0. Original features `session_id  product_id  amount` are all `NaN` as well.

If `transactions_df['cutoff_time'] = transactions_df['transaction_time']` (no time delta), this code produces proper values but includes the current row.

I also submitted it as a [question on SO](https://stackoverflow.com/questions/51191665/excluding-the-current-row-from-feature-engineering-in-python-featuretools), but the code above seems to be right. For example, [the handling time example](https://docs.featuretools.com/automated_feature_engineering/handling_time.html?#running-dfs-with-training-windows) works because the cutoff times are set for the entity we group by. It also produces some `NaN`s, which I think must be zeros:

```py
#!/usr/bin/env python3

import featuretools as ft

es = ft.demo.load_mock_customer(return_entityset=True)

import pandas as pd

cutoff_times = pd.DataFrame({
    "customer_id": [1, 2, 3, 4, 5],
    "time": pd.date_range('2014-01-01 01:41:50', periods=5, freq='25min')
})

feature_matrix, features = ft.dfs(
    entityset=es,
    target_entity="customers",
    cutoff_time=cutoff_times
)

print(feature_matrix)
```

```
             STD(transactions.amount)  MAX(transactions.amount)  \
customer_id                                                       
1                           43.143511                    148.14   
2                           41.140046                    139.23   
3                           45.708958                    147.73   
4                                 NaN                       NaN   
5                           39.139809                    141.66   
```

**Comment by kmax12** [comment] 2018-07-05 20:38
@antontarasenko This is intended behavior for this case, but I put up an [answer on StackOverflow](https://stackoverflow.com/questions/51191665/excluding-the-current-row-from-feature-engineering-in-python-featuretools) to your question. 

I'm going to close this issue, but we can continue discussing on StackOverflow. 

Thanks for posting this question. We're happy to help

**Closed** 2018-07-05 20:38 UTC
